title: Käser
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: some, keywords, here

baseurl: ""
assets_base_url: "assets/"

markdown: kramdown
source: src
destination: dist

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - webpack.config.js
  - Procfile.development
  - npm-debug.log
  - node_modules
  - bin
